import { FileText, AlertTriangle, TrendingUp, Users } from "lucide-react"

// Analytics Cards Data
export const analytics_cards_data = [
  {
    title: "Total Documents",
    value: "1,234",
    change: "+12% from last month",
    icon: FileText,
    iconColor: "text-blue-600",
    trend: "up" as const,
    description: "Active documents",
    badge: "Active",
  },
  {
    title: "High Risk Documents",
    value: "23",
    change: "-5% from last month",
    icon: AlertTriangle,
    iconColor: "text-red-600",
    trend: "down" as const,
    description: "Requires attention",
    badge: "Critical",
  },
  {
    title: "Active Reviews",
    value: "156",
    change: "+8% from last month",
    icon: Users,
    iconColor: "text-green-600",
    trend: "up" as const,
    description: "In progress",
    badge: "Ongoing",
  },
  {
    title: "Monthly Growth",
    value: "18%",
    change: "+3% from last month",
    icon: TrendingUp,
    iconColor: "text-purple-600",
    trend: "up" as const,
    description: "Document volume",
    badge: "Growth",
  },
]

// Mock Documents Data
export const mock_documents_data = [
  {
    id: "doc_001",
    title: "Software License Agreement - Microsoft Office 365",
    type: "License Agreement",
    date: "2024-01-15",
    status: "Approved",
    risk_score: "15",
    last_modified: "2024-01-20",
    author: "John Smith",
    description: "Comprehensive software licensing agreement for Microsoft Office 365 enterprise subscription.",
  },
  {
    id: "doc_002",
    title: "Employment Contract - Senior Developer Position",
    type: "Employment Contract",
    date: "2024-01-18",
    status: "Pending Review",
    risk_score: "45",
    last_modified: "2024-01-22",
    author: "Sarah Johnson",
    description: "Standard employment contract template for senior developer role with equity compensation.",
  },
  {
    id: "doc_003",
    title: "Non-Disclosure Agreement - TechCorp Partnership",
    type: "NDA",
    date: "2024-01-20",
    status: "Flagged",
    risk_score: "85",
    last_modified: "2024-01-25",
    author: "Mike Davis",
    description: "Mutual non-disclosure agreement for strategic partnership discussions with TechCorp.",
  },
  {
    id: "doc_004",
    title: "Service Level Agreement - Cloud Infrastructure",
    type: "SLA",
    date: "2024-01-22",
    status: "Approved",
    risk_score: "25",
    last_modified: "2024-01-28",
    author: "Emily Chen",
    description: "Service level agreement defining uptime guarantees and support terms for cloud services.",
  },
  {
    id: "doc_005",
    title: "Vendor Agreement - Marketing Services",
    type: "Vendor Agreement",
    date: "2024-01-25",
    status: "Pending Review",
    risk_score: "55",
    last_modified: "2024-01-30",
    author: "David Wilson",
    description: "Comprehensive vendor agreement for digital marketing and advertising services.",
  },
  {
    id: "doc_006",
    title: "Data Processing Agreement - GDPR Compliance",
    type: "DPA",
    date: "2024-01-28",
    status: "Approved",
    risk_score: "20",
    last_modified: "2024-02-02",
    author: "Lisa Anderson",
    description: "Data processing agreement ensuring GDPR compliance for customer data handling.",
  },
  {
    id: "doc_007",
    title: "Lease Agreement - Office Space Downtown",
    type: "Lease Agreement",
    date: "2024-02-01",
    status: "Flagged",
    risk_score: "75",
    last_modified: "2024-02-05",
    author: "Robert Taylor",
    description: "Commercial lease agreement for downtown office space with renewal options.",
  },
  {
    id: "doc_008",
    title: "Partnership Agreement - Strategic Alliance",
    type: "Partnership Agreement",
    date: "2024-02-03",
    status: "Pending Review",
    risk_score: "65",
    last_modified: "2024-02-08",
    author: "Jennifer Brown",
    description: "Strategic partnership agreement for joint product development and market expansion.",
  },
  {
    id: "doc_009",
    title: "Terms of Service - Customer Portal",
    type: "Terms of Service",
    date: "2024-02-05",
    status: "Approved",
    risk_score: "10",
    last_modified: "2024-02-10",
    author: "Mark Thompson",
    description: "Terms of service governing customer use of online portal and digital services.",
  },
  {
    id: "doc_010",
    title: "Acquisition Agreement - Startup Purchase",
    type: "Acquisition Agreement",
    date: "2024-02-08",
    status: "Flagged",
    risk_score: "90",
    last_modified: "2024-02-12",
    author: "Amanda White",
    description: "Asset purchase agreement for acquiring innovative AI startup company.",
  },
  {
    id: "doc_011",
    title: "Consulting Agreement - Legal Advisory Services",
    type: "Consulting Agreement",
    date: "2024-02-10",
    status: "Approved",
    risk_score: "30",
    last_modified: "2024-02-15",
    author: "Michael Brown",
    description: "Professional consulting agreement for ongoing legal advisory services.",
  },
  {
    id: "doc_012",
    title: "Franchise Agreement - Restaurant Chain",
    type: "Franchise Agreement",
    date: "2024-02-12",
    status: "Pending Review",
    risk_score: "60",
    last_modified: "2024-02-18",
    author: "Jessica Wilson",
    description: "Franchise agreement for new restaurant location with territorial rights.",
  },
]
